name: Update Instagram Feedname: Update Instagram feed



on:on:

  schedule:  schedule:

    # Esegue ogni 6 ore    - cron: '0 8 * * *' # every day at 08:00 UTC

    - cron: '0 */6 * * *'  workflow_dispatch:

  workflow_dispatch: # Permette esecuzione manuale

jobs:

jobs:  fetch:

  update-instagram:    runs-on: ubuntu-latest

    runs-on: ubuntu-latest    steps:

      - uses: actions/checkout@v4

    steps:

    - name: Checkout repository      - name: Setup Python

      uses: actions/checkout@v4        uses: actions/setup-python@v4

        with:

    - name: Set up Python          python-version: '3.10'

      uses: actions/setup-python@v4

      with:      - name: Install instaloader

        python-version: '3.9'        run: |

          python -m pip install --upgrade pip

    - name: Install Instaloader          pip install instaloader

      run: |

        python -m pip install --upgrade pip      - name: Fetch Instagram posts with Instaloader

        name: Update Instagram Feed

        on:
          schedule:
            # Esegue ogni 6 ore
            - cron: '0 */6 * * *'
          workflow_dispatch: # Permette esecuzione manuale

        jobs:
            # This workflow was replaced by `fetch-instagram-graph.yml`.
            # Kept only to avoid accidental runs of an old broken file.
            # Please remove after you confirm `fetch-instagram-graph.yml` works.
          update-instagram:
            runs-on: ubuntu-latest

            steps:
              - name: Checkout repository
                uses: actions/checkout@v4

              - name: Set up Python
                uses: actions/setup-python@v4
                with:
                  python-version: '3.10'

              - name: Install Instaloader
                run: |
                  python -m pip install --upgrade pip
                  pip install instaloader

              - name: Download Instagram posts
                run: |
                  # Crea cartella temporanea
                  mkdir -p temp_instagram
                  # Prova a scaricare gli ultimi 3 post (per profili pubblici funziona senza login)
                  instaloader --no-videos --no-compress-json --no-profile-pic --no-metadata-json --dirname-pattern=temp_instagram --filename-pattern="{shortcode}" --count=3 lavanderia_angela_
                env:
                  INSTALOADER_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
                  INSTALOADER_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}

              - name: Process Instagram data
                run: |
                  python3 - <<'PY'
        import json
        import os

        user_folder = None
        for item in os.listdir('.'):
            if item.startswith('lavanderia_angela_'):
                user_folder = item
                break

        if not user_folder:
            print('Nessuna cartella Instagram trovata')
            exit(0)

        posts = []
        post_files = [f for f in os.listdir(user_folder) if f.endswith('.json')]

        for post_file in sorted(post_files, reverse=True)[:3]:
            with open(os.path.join(user_folder, post_file), 'r', encoding='utf-8') as f:
                post_data = json.load(f)
            post = {
                'id': post_data.get('id', ''),
                'image': f'https://www.instagram.com/p/{post_data.get("shortcode", "")}/media/?size=l',
                'link': f'https://www.instagram.com/p/{post_data.get("shortcode", "")}/',
                'caption': post_data.get('edge_media_to_caption', {}).get('edges', [{}])[0].get('node', {}).get('text', ''),
                'timestamp': post_data.get('taken_at_timestamp', 0)
            }
            posts.append(post)

        os.makedirs('data', exist_ok=True)
        with open('data/instagram.json', 'w', encoding='utf-8') as f:
            json.dump({'items': posts}, f, ensure_ascii=False, indent=2)

        print(f'Aggiornati {len(posts)} post Instagram')
        PY

              - name: Commit and push changes
                run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add data/instagram.json
                  git commit -m "Update Instagram feed data" || echo "No changes to commit"
                  git push