name: Update Instagram feed

on:
  schedule:
    - cron: '0 8 * * *' # every day at 08:00 UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install instaloader
        run: |
          python -m pip install --upgrade pip
          pip install instaloader

      - name: Fetch Instagram posts with Instaloader
        run: |
          mkdir -p data
          instaloader --no-videos --no-profile-pic --no-compress-json --no-metadata-json --dirname-pattern=temp_instagram --filename-pattern="{shortcode}" --count=3 lavanderia_angela_
          python3 fetch_instagram_to_json.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet data/instagram.json; then
            echo "No changes to commit"
          else
            git add data/instagram.json
            git commit -m "Update Instagram feed"
            git push
          fi
