name: Update Instagram Feed (Disabled)

on:
  workflow_dispatch: # Only manual, but disabled

jobs:
  disabled:
    runs-on: ubuntu-latest
    if: false  # Always skip
    steps:
      - run: echo "This workflow is disabled. Use fetch-instagram-graph.yml instead."