name: Update Instagram feed

on:
  schedule:
    - cron: '0 8 * * *' # every day at 08:00 UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Instagram feed
        uses: smatak/instagram-action@v2
        with:
          username: lavanderia_angela_
          output_file: data/instagram.json

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet data/instagram.json; then
            echo "No changes to commit"
          else
            git add data/instagram.json
            git commit -m "Update Instagram feed"
            git push
          fi
