name: Update Instagram feed

on:
  schedule:
    - cron: '0 8 * * *' # every day at 08:00 UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install instaloader
        run: |
          python -m pip install --upgrade pip
          pip install instaloader

      - name: Fetch Instagram posts with Instaloader
        run: |
          mkdir -p data
          # Use instaloader to download the last 3 posts into a temp folder
          instaloader --no-videos --no-profile-pic --no-compress-json --no-metadata-json --dirname-pattern=temp_instagram --filename-pattern="{shortcode}" --count=3 lavanderia_angela_
          python - <<'PY'
import json, os, glob
posts = []
for path in sorted(glob.glob('temp_instagram/*.json')):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        shortcode = data.get('shortcode')
        # find jpg with same name
        jpg = None
        for ext in ('.jpg', '.jpeg', '.png'):
            candidate = f'temp_instagram/{shortcode}{ext}'
            if os.path.exists(candidate):
                jpg = candidate
                break
        if jpg:
            # move to data folder and use relative path
            dst = os.path.join('data', os.path.basename(jpg))
            os.replace(jpg, dst)
            posts.append({
                'id': shortcode,
                'image': dst.replace('\\', '/'),
                'link': f'https://www.instagram.com/p/{shortcode}/',
                'caption': data.get('edge_media_to_caption', {}).get('edges', [{}])[0].get('node', {}).get('text', '')
            })
    except Exception as e:
        print('skip', path, e)
with open('data/instagram.json', 'w', encoding='utf-8') as f:
    json.dump({'items': posts}, f, ensure_ascii=False, indent=2)
PY

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet data/instagram.json; then
            echo "No changes to commit"
          else
            git add data/instagram.json
            git commit -m "Update Instagram feed"
            git push
          fi
